name: Tag

on:
  push:
    branches: ['master']
    paths:
      - "lib/**/version.rb"

jobs:
  release:
    name: Create a tag
    uses: stejskalleos/foreman_actions/.github/workflows/create_tag.yml@v0
    with:
      allowed_owner: "theforeman"
