name: Update translations

on:
  workflow_dispatch:

jobs:
  tx-update:
    name: Update translations
    uses: stejskalleos/foreman_actions/.github/workflows/tx-hammer-plugins.yml@hammer-tx
    with:
      plugin_name: "hammer-cli-foreman-google"
      tx_token: "${{ secrets.GITHUB_TOKEN }}"
      gh_token: "${{ secrets.TX_TOKEN }}"
