name: Pull translations

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hammer-cli-foreman-google
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7]

    steps:
         
      - name: Get hammer-cli-foreman-google
        uses: actions/checkout@v4
        with:
          path: hammer-cli-foreman-google
          
      - name: "Run action"
        with:
            tx_token: ${{ secrets.TX_TOKEN }}
            git_flow: true
            github_token: ${{ secrets.GITHUB_TOKEN }}
            translations_folder: locale
            pull_translations: true
            pull_sources: true
            push_translations: false
            push_sources: false
            path: hammer-cli-foreman-google
        uses: docker://sergioisidoro/github-transifex-action:latest
