name: Pull translations

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hammer-cli-foreman-google
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7]

    steps:
         
      - name: Get hammer-cli-foreman-google
        uses: actions/checkout@v4          
      - name: "Run action"
        run: |
          echo ${{ secrets.TX_TOKEN }}
