name: Update translations

on:
  workflow_dispatch:

jobs:
  tx-update:
    name: Update translations
    uses: stejskalleos/actions/.github/workflows/tx-hammer-plugins.yml@hammer-tx
    with:
      plugin_name: hammer-cli-foreman-google
