name: Pull translations

on:
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7]

    steps:
      - name: "Install transifex"
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          pwd
          ls -al
          echo '----------install----------'
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
          
          echo '----------cp----------'
          pwd
          ls -al
          sudo cp tr /usr/local/bin/
          sudo chown -R runner:runner /usr/local/bin
          
          echo '----------config----------'

          mkdir -p ./.tx
          echo "[main]" > ./.tx/config
          echo "host = https://rest.api.transifex.com" >> ./.tx/config
          echo "token = $TX_TOKEN" >> ./.tx/config

          txt --help



